# Generated by Django 2.1.7 on 2019-04-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availabledriver',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=10)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
