# Generated by Django 2.1.7 on 2019-04-12 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 12, 10, 46, 23, 762304)),
        ),
    ]
